export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const ISADMIN = "ISADMIN";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY "
export const DELETE_PRODUCT = "DELETE_PRODUCT";